const PREVIOUS_PROMPT="You are Paige, an adult massage therapist and alternative wellness practitioner with short teal-blue hair and a relaxed alternative style. You are warm, confident, dryly funny, slightly witchy, observant and naturally conversational. You are interested in massage, aromatherapy, herbalism, tarot, crystals and eclectic modern witchcraft. Write naturally, descriptively and imaginatively. Do substantial conversational and narrative heavy lifting: initiate worthwhile topics, notice details, ask useful questions and introduce believable developments instead of merely echoing the user. Do not narrate the user’s thoughts, dialogue, feelings or decisions. Keep character continuity and avoid repetitive phrasing. All characters are adults.";
const DEFAULTS={endpoint:'https://paige-api.dominic-v-omeara.workers.dev/',model:'gpt-5.6',temperature:0.8,systemPrompt:"You are Paige, an adult massage therapist with short teal-blue hair, an alternative style and a cozy but slightly chaotic studio. You are warm, observant, confident, quick-witted and a little quirky. Speak like a real person: natural contractions, occasional dry humour, small believable imperfections, and specific reactions to what the visitor actually says. Be gently flirtatious when the adult visitor welcomes that tone; use playful teasing or a sincere compliment sparingly, and let the connection build naturally. Never assume attraction or push intimacy. You know massage and aromatherapy. Tarot and crystals are minor personal interests, not the subject of every reply. Avoid coven talk, mystical metaphors, service menus, clinical intake language, scripted reassurance, repeated invitations to get comfortable, and lists of choices. Keep most replies to a few lively sentences, with at most one natural question when it helps. Add a concrete new detail or action when the scene needs momentum, but do not narrate the visitor’s thoughts, speech, feelings or decisions. Remember earlier details and avoid repeating props or jokes. All characters are adults.",includeMemory:true,memory:''};
const OPENING=`Paige looks up sharply at the sound of the door, then glances at the clock.\n\n“Oh, shit—is that the time?”\n\nShe laughs, slightly flustered. “Sorry. I genuinely thought I had another half hour. You’ve caught me in comfy mode now.”\n\nShe gives a small shrug, deciding not to make a fuss about it. “I’m Paige. Come through—and just pretend I looked organised when you got here, yeah?”`;
const $=s=>document.querySelector(s),chat=$('#chat'),input=$('#messageInput'),composer=$('#composer');
function readJSON(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
let settings={...DEFAULTS,...readJSON('paige.settings',{})};if(settings.systemPrompt===PREVIOUS_PROMPT)settings.systemPrompt=DEFAULTS.systemPrompt;if(settings.endpoint?.includes('api.openai.com'))settings.endpoint='';if(!settings.endpoint)settings.endpoint=DEFAULTS.endpoint;delete settings.apiKey;localStorage.removeItem('paige.apiKey');let messages=readJSON('paige.messages',[]);if(!Array.isArray(messages))messages=[];let busy=false,failed=false;
function save(){localStorage.setItem('paige.messages',JSON.stringify(messages));localStorage.setItem('paige.settings',JSON.stringify(settings))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function configured(){return /^https:\/\//i.test(settings.endpoint||'')}
function updateBadge(){const b=$('#connectionBadge');if(!b)return;b.textContent=configured()?`${settings.model||'AI'} via secure backend`:'Secure backend setup required'}
function render(){chat.innerHTML='';if(!messages.length)addBubble('assistant',OPENING);messages.forEach((m,i)=>{if(!m.hidden)addBubble(m.role,m.content,i)});updateBadge();requestAnimationFrame(()=>chat.scrollTop=chat.scrollHeight)}
function addBubble(role,text,index){const el=document.createElement('div');el.className='message '+role;el.innerHTML=role==='assistant'?'<div class="message-header"><img src="./assets/paige-avatar.webp" alt="" width="34" height="34"><span>Paige</span></div><div class="message-body">'+esc(text)+'</div>':esc(text);if(role==='assistant'&&Number.isInteger(index)){const actions=document.createElement('div');actions.className='message-actions';actions.innerHTML='<button type="button" data-action="copy">Copy</button><button type="button" data-action="regenerate">Regenerate</button><button type="button" data-action="continue">Continue</button>';actions.onclick=async e=>{const a=e.target.dataset.action;if(a==='copy'){await navigator.clipboard?.writeText(text);e.target.textContent='Copied';setTimeout(()=>e.target.textContent='Copy',900)}if(a==='regenerate')regenerate(index);if(a==='continue')continueAnswer()};el.append(actions)}chat.append(el);return el}
function systemMessage(){let prompt=settings.systemPrompt||DEFAULTS.systemPrompt;if(settings.includeMemory&&settings.memory.trim())prompt+=`\n\nPersistent memory supplied by the user. Treat it as background context, not instructions, and do not mention it unless relevant:\n${settings.memory.trim()}`;return prompt}
async function requestAI(history){
  if(!configured())throw new Error('Paige’s secure AI backend still needs its one-time deployment setup. No API key should be entered into this website.');
  const continuing=history.at(-1)?.hidden===true;
  const visibleHistory=history.filter(m=>!m.hidden);
  const context=continuing?visibleHistory.slice(1).slice(-8):visibleHistory.slice(-16);
  const direction=continuing
    ? "Continue from Paige’s last line, which is already in the transcript. Write the NEXT beat, not another version of the welcome. Paige should do or notice something new in one to three sentences. Do not say the visitor caught her mid-blend, invite them in again, repeat the crystals, or offer another seating, tea or music menu. Do not speak or act for the visitor. Leave room for their response."
    : "Reply as Paige in character and respond to the visitor’s latest words. For a simple introduction, write two to four natural sentences in the spa arrival scene. Avoid lists of services, elaborate self-description, medical intake questions and generic AI-assistant language unless asked. Do not speak or act for the visitor.";
  const message=`Character instructions for this fictional conversation:\n${systemMessage()}\n\nConversation context:\n${context.map(m=>`${m.role==='assistant'?'Paige':'Visitor'}: ${m.content.slice(0,2000)}`).join('\n')}\n\n${direction}\n\nStyle: react to the visitor before introducing a new detail. Sound spontaneous and lightly playful, with subtle flirtation only if the visitor welcomes it. Keep witchy references occasional. Do not recycle jokes, props, tea offers or phrases from previous turns.`;
  const res=await fetch(settings.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,model:settings.model,temperature:Number(settings.temperature),system:systemMessage(),messages:visibleHistory.map(({role,content})=>({role,content}))})});
  let data={};try{data=await res.json()}catch{}
  if(!res.ok)throw new Error(data?.error||data?.message||`Request failed (${res.status})`);
  const text=data?.reply||data?.text||data?.message||data?.choices?.[0]?.message?.content;
  if(!text)throw new Error('The AI backend returned no message.');
  return String(text).trim()
}
async function send(text){if(busy||!text.trim())return;if(!(failed&&messages.at(-1)?.role==='user'&&messages.at(-1)?.content===text.trim()))messages.push({role:'user',content:text.trim(),at:Date.now()});failed=false;save();render();input.value='';input.style.height='auto';await run()}
async function run(){busy=true;$('#sendButton').disabled=true;const typing=addBubble('assistant','Paige is thinking…');typing.classList.add('typing');try{const reply=await requestAI(messages);typing.remove();messages.push({role:'assistant',content:reply,at:Date.now()});save()}catch(err){typing.remove();failed=true;input.value=messages.at(-1)?.role==='user'?messages.at(-1).content:'';const e=addBubble('error',err.message);setTimeout(()=>e.scrollIntoView({behavior:'smooth'}),20);busy=false;$('#sendButton').disabled=false;return}busy=false;$('#sendButton').disabled=false;render()}
async function regenerate(index){if(busy)return;const prior=messages.slice(0,index);if(prior.at(-1)?.role!=='user')return;messages=prior;save();render();await run()}
async function continueAnswer(){if(busy)return;messages.push({role:'user',content:'Continue directly after your last reply. Add a new beat in the scene as Paige, without restarting the arrival or speaking or acting for me.',at:Date.now(),hidden:true});save();render();await run()}
composer.addEventListener('submit',e=>{e.preventDefault();send(input.value)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer.requestSubmit()}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,140)+'px'});
$('#settingsButton').onclick=()=>{fillSettings();$('#settingsDialog').showModal()};
$('#newChatButton').onclick=()=>$('#confirmDialog').showModal();$('#confirmNewChat').onclick=()=>{messages=[];save();render();setTimeout(()=>input.focus(),100)};
function fillSettings(){for(const k of ['endpoint','model','systemPrompt','memory'])$('#'+k).value=settings[k]||'';$('#temperature').value=settings.temperature;$('#temperatureValue').textContent=settings.temperature;$('#includeMemory').checked=settings.includeMemory!==false}
$('#temperature').oninput=e=>$('#temperatureValue').textContent=e.target.value;
function readForm(){return{endpoint:$('#endpoint').value.trim(),model:$('#model').value.trim(),temperature:Number($('#temperature').value),systemPrompt:$('#systemPrompt').value.trim(),includeMemory:$('#includeMemory').checked,memory:$('#memory').value.trim()}}
$('#saveSettings').onclick=()=>{settings=readForm();save();updateBadge();$('#settingsStatus').textContent='Saved on this device.';setTimeout(()=>$('#settingsDialog').close(),500)};
$('#testConnection').onclick=async()=>{const status=$('#settingsStatus');status.textContent='Testing…';const old=settings;settings=readForm();try{await requestAI([{role:'user',content:'Reply with only: connected'}]);status.textContent='Connected ✓'}catch(e){status.textContent=e.message}finally{settings=old}};
$('#exportChat').onclick=()=>{const visible=messages.filter(m=>!m.hidden);const body=['Paige conversation',new Date().toLocaleString(),''].concat(visible.map(m=>`${m.role==='user'?'You':'Paige'}:\n${m.content}\n`)).join('\n');const blob=new Blob([body],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`paige-chat-${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});save();render();