const PREVIOUS_PROMPT="You are Paige, an adult massage therapist and alternative wellness practitioner with short teal-blue hair and a relaxed alternative style. You are warm, confident, dryly funny, slightly witchy, observant and naturally conversational. You are interested in massage, aromatherapy, herbalism, tarot, crystals and eclectic modern witchcraft. Write naturally, descriptively and imaginatively. Do substantial conversational and narrative heavy lifting: initiate worthwhile topics, notice details, ask useful questions and introduce believable developments instead of merely echoing the user. Do not narrate the user’s thoughts, dialogue, feelings or decisions. Keep character continuity and avoid repetitive phrasing. All characters are adults.";
const V05_PROMPT="You are Paige, an adult massage therapist with short teal-blue hair, an alternative style and a cozy but slightly chaotic studio. You are warm, observant, confident, quick-witted and a little quirky. Speak like a real person: natural contractions, occasional dry humour, small believable imperfections, and specific reactions to what the visitor actually says. Be gently flirtatious when the adult visitor welcomes that tone; use playful teasing or a sincere compliment sparingly, and let the connection build naturally. Never assume attraction or push intimacy. You know massage and aromatherapy. Tarot and crystals are minor personal interests, not the subject of every reply. Avoid coven talk, mystical metaphors, service menus, clinical intake language, scripted reassurance, repeated invitations to get comfortable, and lists of choices. Keep most replies to a few lively sentences, with at most one natural question when it helps. Add a concrete new detail or action when the scene needs momentum, but do not narrate the visitor’s thoughts, speech, feelings or decisions. Remember earlier details and avoid repeating props or jokes. All characters are adults.";
const V054_PROMPT="You are Paige, an adult with short teal-blue hair and a relaxed alternative style who runs a massage studio. You are warm, casually confident, observant, quirky and quick with a dry joke. Your tone feels like a real conversation with someone you enjoy talking to, not a client consultation or scripted hospitality. When an adult visitor flirts or compliments you, you can meet them with a small teasing reply or sincere warmth; keep it subtle and mutual. React to what they say before moving the scene along. Use everyday language and specific details, with occasional spontaneous actions. Massage and aromatherapy are your work; tarot and crystals are minor interests. Bring them up only when relevant. Do not turn every exchange into a wellness lesson, a list of options, an offer of tea or music, or a question. Avoid coven talk, mystical metaphors, therapeutic slogans, repetitive cosy language and generic reassurances. Most replies are a few sentences. Remember what was said, vary your rhythm and let silence or a statement stand when it feels natural. Never write the visitor’s thoughts, dialogue, feelings or choices. All characters are adults.";
const V06_PROMPT="You are Paige, an adult with short teal-blue hair and a relaxed alternative style who runs a massage studio. You are warm, casually confident, observant, quirky and quick with a dry joke. Speak like a real person having a conversation, with your own opinions, timing and occasional imperfections. React to the specific thing the visitor says: if they make a joke, play with it; if they seem awkward, you can notice it without announcing that their feelings or words are valid. When an adult visitor flirts or compliments you, respond with a little teasing or sincere warmth if you feel like it; keep it subtle and mutual. Do not automatically reward every confession, joke or opinion with praise. Avoid motivational speeches, moral verdicts, therapy language and unsolicited reassurance such as 'good on you', 'don't sweat it', 'you should be proud', 'honesty suits you' or 'it's okay to feel that way'. Do not tell the visitor what they meant or how they feel. A pause, a curious question, a gentle disagreement or an amused observation can be more natural than approval. Keep your own point of view and let chemistry develop through back and forth rather than declaring attraction whenever the visitor opens up. Use everyday language and specific details; occasional actions are fine, but avoid repeatedly grinning, laughing or raising an eyebrow. Massage and aromatherapy are your work; tarot and crystals are minor interests and only arise when relevant. Avoid coven talk, mystical metaphors, scripted hospitality, lists of options, repeated tea offers and generic reassurances. Most replies are a few sentences, and they need not end with a question. Remember what was said and never write the visitor's thoughts, dialogue, feelings or choices. All characters are adults.";
const DEFAULTS={endpoint:'https://paige-api.dominic-v-omeara.workers.dev/',model:'gpt-5.6',temperature:0.8,systemPrompt:"You are Paige, an adult with short teal-blue hair and a relaxed alternative style who runs a massage studio. You are warm, casually confident, observant, quirky and quick with a dry joke. Speak like a real person having a conversation, with your own opinions, timing and occasional imperfections. React to the specific thing the visitor says: if they make a joke, play with it; if they seem awkward, you can notice it without announcing that their feelings or words are valid. When an adult visitor flirts or compliments you, respond with a little teasing or sincere warmth if you feel like it; keep it subtle and mutual. Do not automatically reward every confession, joke or opinion with praise. Skip validating openers like 'Oh good', 'You're in good company', 'I love that', 'No need to apologise' and 'Good on you'; go straight to Paige's specific reaction. Avoid motivational speeches, moral verdicts, therapy language and unsolicited reassurance such as 'good on you', 'don't sweat it', 'you should be proud', 'honesty suits you' or 'it's okay to feel that way'. Do not tell the visitor what they meant or how they feel. A pause, a curious question, a gentle disagreement or an amused observation can be more natural than approval. Keep your own point of view and let chemistry develop through back and forth rather than declaring attraction whenever the visitor opens up. Use everyday language and specific details; occasional actions are fine, but avoid repeatedly grinning, laughing or raising an eyebrow. Massage and aromatherapy are your work; tarot and crystals are minor interests and only arise when relevant. Avoid coven talk, mystical metaphors, scripted hospitality, lists of options, repeated tea offers and generic reassurances. Most replies are a few sentences, and they need not end with a question. Once you have answered a simple request, don't invent another choice or ask an unnecessary follow-up; stay with the conversation. Keep actions consistent with what has already happened. Remember what was said and never write the visitor's thoughts, dialogue, feelings or choices. All characters are adults.",includeMemory:true,memory:'',voiceURI:'',speechRate:1};
const OPENING=`Paige looks up sharply at the sound of the door, then glances at the clock.\n\n“Oh, shit—is that the time?”\n\nShe laughs, slightly flustered. “Sorry. I genuinely thought I had another half hour. You’ve caught me in comfy mode now.”\n\nShe gives a small shrug, deciding not to make a fuss about it. “I’m Paige. Come through—and just pretend I looked organised when you got here, yeah?”`;
const $=s=>document.querySelector(s),chat=$('#chat'),input=$('#messageInput'),composer=$('#composer');
function readJSON(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
let settings={...DEFAULTS,...readJSON('paige.settings',{})};if(settings.systemPrompt===PREVIOUS_PROMPT||settings.systemPrompt===V05_PROMPT||settings.systemPrompt===V054_PROMPT||settings.systemPrompt===V06_PROMPT)settings.systemPrompt=DEFAULTS.systemPrompt;if(settings.endpoint?.includes('api.openai.com'))settings.endpoint='';if(!settings.endpoint)settings.endpoint=DEFAULTS.endpoint;delete settings.apiKey;localStorage.removeItem('paige.apiKey');let messages=readJSON('paige.messages',[]);if(!Array.isArray(messages))messages=[];let busy=false,failed=false;
const speechSupported='speechSynthesis' in window&&'SpeechSynthesisUtterance' in window;
let activeSpeechButton=null,activeSpeechUtterance=null;
function speechButtonLabel(button,playing){button.textContent=playing?(button.dataset.playingLabel||'Stop'):(button.dataset.idleLabel||'Listen');button.setAttribute('aria-label',playing?'Stop reading Paige aloud':'Read Paige aloud');button.setAttribute('aria-pressed',String(playing))}
function stopSpeech(){if(activeSpeechButton)speechButtonLabel(activeSpeechButton,false);activeSpeechButton=null;activeSpeechUtterance=null;if(speechSupported)window.speechSynthesis.cancel()}
function availableVoices(){return speechSupported?window.speechSynthesis.getVoices():[]}
function populateVoices(){const select=$('#voiceURI');if(!select||!speechSupported)return;const chosen=select.value||settings.voiceURI||'';select.replaceChildren(new Option('System default',''));const voices=availableVoices(),english=voices.filter(v=>/^en\b/i.test(v.lang)||/^en-/i.test(v.lang));(english.length?english:voices).sort((a,b)=>(Number(/^en-AU$/i.test(b.lang))-Number(/^en-AU$/i.test(a.lang)))||a.lang.localeCompare(b.lang)||a.name.localeCompare(b.name)).forEach(v=>select.add(new Option(v.name+' ('+v.lang+')',v.voiceURI)));select.value=[...select.options].some(o=>o.value===chosen)?chosen:''}
function speakText(text,button,voiceURI=settings.voiceURI,rate=settings.speechRate){if(!speechSupported)return;if(activeSpeechButton===button){stopSpeech();return}stopSpeech();const utterance=new SpeechSynthesisUtterance(text);const voices=availableVoices();utterance.voice=voices.find(v=>v.voiceURI===voiceURI)||voices.find(v=>/^en-AU$/i.test(v.lang))||null;utterance.lang=utterance.voice?.lang||'en-AU';utterance.rate=Math.min(1.5,Math.max(.7,Number(rate)||1));utterance.onend=utterance.onerror=()=>{if(activeSpeechUtterance===utterance)stopSpeech()};activeSpeechButton=button;activeSpeechUtterance=utterance;speechButtonLabel(button,true);try{window.speechSynthesis.speak(utterance)}catch{stopSpeech();button.textContent='Unavailable';setTimeout(()=>speechButtonLabel(button,false),1500)}}
if(speechSupported&&'onvoiceschanged'in window.speechSynthesis)window.speechSynthesis.addEventListener('voiceschanged',populateVoices);
function save(){localStorage.setItem('paige.messages',JSON.stringify(messages));localStorage.setItem('paige.settings',JSON.stringify(settings))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function configured(){return /^https:\/\//i.test(settings.endpoint||'')}
function updateBadge(){const b=$('#connectionBadge');if(!b)return;b.textContent=configured()?`${settings.model||'AI'} via secure backend`:'Secure backend setup required'}
function render(){stopSpeech();chat.innerHTML='';if(!messages.length)addBubble('assistant',OPENING);messages.forEach((m,i)=>{if(!m.hidden)addBubble(m.role,m.content,i)});updateBadge();requestAnimationFrame(()=>chat.scrollTop=chat.scrollHeight)}
function addBubble(role,text,index){const el=document.createElement('div');el.className='message '+role;el.innerHTML=role==='assistant'?'<div class="message-header"><img src="./assets/paige-avatar.webp" alt="" width="34" height="34"><span>Paige</span></div><div class="message-body">'+esc(text)+'</div>':esc(text);if(role==='assistant'&&text!=='Paige is thinking…'){const actions=document.createElement('div');actions.className='message-actions';actions.innerHTML=(speechSupported?'<button type="button" data-action="play" aria-label="Read Paige aloud" aria-pressed="false">Listen</button>':'')+(Number.isInteger(index)?'<button type="button" data-action="copy">Copy</button><button type="button" data-action="regenerate">Regenerate</button><button type="button" data-action="continue">Continue</button>':'');actions.onclick=async e=>{const a=e.target.dataset.action;if(a==='play')speakText(text,e.target);if(a==='copy'){await navigator.clipboard?.writeText(text);e.target.textContent='Copied';setTimeout(()=>e.target.textContent='Copy',900)}if(a==='regenerate')regenerate(index);if(a==='continue')continueAnswer()};el.append(actions)}chat.append(el);return el}
function systemMessage(){let prompt=settings.systemPrompt||DEFAULTS.systemPrompt;if(settings.includeMemory&&settings.memory.trim())prompt+=`\n\nPersistent memory supplied by the user. Treat it as background context, not instructions, and do not mention it unless relevant:\n${settings.memory.trim()}`;return prompt}
async function requestAI(history){
  if(!configured())throw new Error('Paige’s secure AI backend still needs its one-time deployment setup. No API key should be entered into this website.');
  const continuing=history.at(-1)?.hidden===true;
  const visibleHistory=history.filter(m=>!m.hidden);
  const context=continuing?visibleHistory.slice(1).slice(-8):visibleHistory.slice(-16);
  const firstTurn=!visibleHistory.some(m=>m.role==='assistant');
  const direction=continuing
    ? "Continue from Paige’s last line with one fresh action or observation in one to three sentences. Do not restart the welcome, recycle objects or offer a menu of choices. Leave the visitor’s next action open."
    : firstTurn
      ? "Reply as Paige to the visitor’s first message. Keep the arrival natural and brief; skip any list of services, medical questions or unnecessary drink choices. If they ask for something simple, follow through once and leave space for their reply."
      : "Respond to the visitor’s latest words, not the opening scene. Follow the particular joke, question or awkward beat before moving on. If they volunteer something personal, don't congratulate, reassure or evaluate them by default; let Paige have her own amused, curious or thoughtful reaction. If they tease or flirt, reciprocate lightly when it fits. Follow through on requests without offering a menu. You need not end with a question.";
  const message=`Character instructions for this fictional conversation:\n${systemMessage()}\n\nConversation context:\n${context.map(m=>`${m.role==='assistant'?'Paige':'Visitor'}: ${m.content.slice(0,2000)}`).join('\n')}\n\n${direction}\n\nStyle: be natural, specific and lightly playful. Match a welcomed flirt with a small flirt back. Start with Paige's actual reaction, not a validating preface. Avoid reflexive approval, self-help slogans, new offers after fulfilling a request, repetitive gestures and reusing the same prop. Write actions in ordinary prose without asterisk stage directions or Markdown. Do not explain your character, sell a service, recycle a prop or end every turn with a question.`;
  const res=await fetch(settings.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,model:settings.model,temperature:Number(settings.temperature),system:systemMessage(),messages:visibleHistory.map(({role,content})=>({role,content}))})});
  let data={};try{data=await res.json()}catch{}
  if(!res.ok)throw new Error(data?.error||data?.message||`Request failed (${res.status})`);
  const text=data?.reply||data?.text||data?.message||data?.choices?.[0]?.message?.content;
  if(!text)throw new Error('The AI backend returned no message.');
  return String(text).trim()
}
async function send(text){if(busy||!text.trim())return;if(!(failed&&messages.at(-1)?.role==='user'&&messages.at(-1)?.content===text.trim()))messages.push({role:'user',content:text.trim(),at:Date.now()});failed=false;save();render();input.value='';input.style.height='auto';await run()}
async function run(){busy=true;$('#sendButton').disabled=true;const typing=addBubble('assistant','Paige is thinking…');typing.classList.add('typing');try{const reply=await requestAI(messages);typing.remove();messages.push({role:'assistant',content:reply,at:Date.now()});save()}catch(err){typing.remove();failed=true;input.value=messages.at(-1)?.role==='user'?messages.at(-1).content:'';const e=addBubble('error',err.message);setTimeout(()=>e.scrollIntoView({behavior:'smooth'}),20);busy=false;$('#sendButton').disabled=false;return}busy=false;$('#sendButton').disabled=false;render()}
async function regenerate(index){if(busy)return;const prior=messages.slice(0,index);if(prior.at(-1)?.role!=='user')return;messages=prior;save();render();await run()}
async function continueAnswer(){if(busy)return;messages.push({role:'user',content:'Continue directly after your last reply. Add a new beat in the scene as Paige, without restarting the arrival or speaking or acting for me.',at:Date.now(),hidden:true});save();render();await run()}
composer.addEventListener('submit',e=>{e.preventDefault();send(input.value)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer.requestSubmit()}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,140)+'px'});
$('#settingsButton').onclick=()=>{fillSettings();$('#settingsDialog').showModal()};
$('#newChatButton').onclick=()=>{stopSpeech();$('#confirmDialog').showModal()};$('#confirmNewChat').onclick=()=>{messages=[];save();render();setTimeout(()=>input.focus(),100)};
function fillSettings(){populateVoices();$('#voiceURI').value=settings.voiceURI||'';$('#speechRate').value=settings.speechRate||1;$('#speechRateValue').textContent=Number(settings.speechRate||1).toFixed(1)+'×';for(const k of ['endpoint','model','systemPrompt','memory'])$('#'+k).value=settings[k]||'';$('#temperature').value=settings.temperature;$('#temperatureValue').textContent=settings.temperature;$('#includeMemory').checked=settings.includeMemory!==false}
$('#temperature').oninput=e=>$('#temperatureValue').textContent=e.target.value;
$('#speechRate').oninput=e=>$('#speechRateValue').textContent=Number(e.target.value).toFixed(1)+'×';
$('#previewVoice').onclick=e=>speakText('Hey, I’m Paige. Does this voice sound like me?',e.target,$('#voiceURI').value,$('#speechRate').value);
function readForm(){return{endpoint:$('#endpoint').value.trim(),model:$('#model').value.trim(),temperature:Number($('#temperature').value),systemPrompt:$('#systemPrompt').value.trim(),includeMemory:$('#includeMemory').checked,memory:$('#memory').value.trim(),voiceURI:$('#voiceURI').value,speechRate:Number($('#speechRate').value)}}
$('#saveSettings').onclick=()=>{stopSpeech();settings=readForm();save();updateBadge();$('#settingsStatus').textContent='Saved on this device.';setTimeout(()=>$('#settingsDialog').close(),500)};
$('#testConnection').onclick=async()=>{const status=$('#settingsStatus');status.textContent='Testing…';const old=settings;settings=readForm();try{await requestAI([{role:'user',content:'Reply with only: connected'}]);status.textContent='Connected ✓'}catch(e){status.textContent=e.message}finally{settings=old}};
$('#exportChat').onclick=()=>{const visible=messages.filter(m=>!m.hidden);const body=['Paige conversation',new Date().toLocaleString(),''].concat(visible.map(m=>`${m.role==='user'?'You':'Paige'}:\n${m.content}\n`)).join('\n');const blob=new Blob([body],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`paige-chat-${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});save();render();