const DEFAULTS={endpoint:'https://api.openai.com/v1/chat/completions',model:'gpt-5.6',temperature:0.8,systemPrompt:'You are Paige, an adult massage therapist and alternative wellness practitioner with short teal-blue hair and a relaxed alternative style. You are warm, confident, dryly funny, slightly witchy, observant and naturally conversational. You are interested in massage, aromatherapy, herbalism, tarot, crystals and eclectic modern witchcraft. Write naturally, descriptively and imaginatively. Do substantial conversational and narrative heavy lifting: initiate worthwhile topics, notice details, ask useful questions and introduce believable developments instead of merely echoing the user. Do not narrate the user’s thoughts, dialogue, feelings or decisions. Keep character continuity and avoid repetitive phrasing. All characters are adults.'};
const OPENING=`Paige looks up sharply at the sound of the door, then glances at the clock.\n\n“Oh, shit—is that the time?”\n\nShe laughs, slightly flustered. “Sorry. I genuinely thought I had another half hour. You’ve caught me in comfy mode now.”\n\nShe gives a small shrug, deciding not to make a fuss about it. “I’m Paige. Come through—and just pretend I looked organised when you got here, yeah?”`;
const $=s=>document.querySelector(s),chat=$('#chat'),input=$('#messageInput'),composer=$('#composer');
function readJSON(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
let settings={...DEFAULTS,...readJSON('paige.settings',{})};let messages=readJSON('paige.messages',[]);if(!Array.isArray(messages))messages=[];let busy=false;
function save(){localStorage.setItem('paige.messages',JSON.stringify(messages));localStorage.setItem('paige.settings',JSON.stringify(settings))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){chat.innerHTML='';if(!messages.length)addBubble('assistant',OPENING);messages.forEach((m,i)=>addBubble(m.role,m.content,i));requestAnimationFrame(()=>chat.scrollTop=chat.scrollHeight)}
function addBubble(role,text,index){const el=document.createElement('div');el.className='message '+role;el.innerHTML=esc(text);if(role==='assistant'&&Number.isInteger(index)){const actions=document.createElement('div');actions.className='message-actions';actions.innerHTML='<button type="button" data-action="regenerate">Regenerate</button><button type="button" data-action="continue">Continue</button>';actions.onclick=e=>{if(e.target.dataset.action==='regenerate')regenerate(index);if(e.target.dataset.action==='continue')continueAnswer()};el.append(actions)}chat.append(el);return el}
async function requestAI(history){if(!settings.apiKey&&settings.endpoint.includes('api.openai.com'))throw new Error('Add your API key in AI Settings first.');const headers={'Content-Type':'application/json'};if(settings.apiKey)headers.Authorization='Bearer '+settings.apiKey;const res=await fetch(settings.endpoint,{method:'POST',headers,body:JSON.stringify({model:settings.model,temperature:Number(settings.temperature),messages:[{role:'system',content:settings.systemPrompt},...history.map(({role,content})=>({role,content}))]})});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data?.error?.message||`Request failed (${res.status})`);const text=data?.choices?.[0]?.message?.content||data?.choices?.[0]?.text;if(!text)throw new Error('The AI provider returned no message.');return text.trim()}
async function send(text){if(busy||!text.trim())return;messages.push({role:'user',content:text.trim()});save();render();input.value='';input.style.height='auto';await run()}
async function run(){busy=true;const typing=addBubble('assistant','Paige is thinking…');typing.classList.add('typing');try{const reply=await requestAI(messages);typing.remove();messages.push({role:'assistant',content:reply});save()}catch(err){typing.remove();const e=addBubble('error',err.message);setTimeout(()=>e.scrollIntoView({behavior:'smooth'}),20);busy=false;return}busy=false;render()}
async function regenerate(index){if(busy)return;const prior=messages.slice(0,index);if(prior.at(-1)?.role!=='user')return;messages=prior;save();render();await run()}
async function continueAnswer(){if(busy)return;messages.push({role:'user',content:'Continue the scene naturally as Paige without requiring me to speak first. Move things forward while leaving my choices open.'});save();render();await run()}
composer.addEventListener('submit',e=>{e.preventDefault();send(input.value)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer.requestSubmit()}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,140)+'px'});
$('#settingsButton').onclick=()=>{fillSettings();$('#settingsDialog').showModal()};
function fillSettings(){for(const k of ['endpoint','model','apiKey','systemPrompt'])$('#'+k).value=settings[k]||'';$('#temperature').value=settings.temperature;$('#temperatureValue').textContent=settings.temperature}
$('#temperature').oninput=e=>$('#temperatureValue').textContent=e.target.value;
$('#saveSettings').onclick=()=>{settings={endpoint:$('#endpoint').value.trim(),model:$('#model').value.trim(),apiKey:$('#apiKey').value.trim(),temperature:Number($('#temperature').value),systemPrompt:$('#systemPrompt').value.trim()};save();$('#settingsStatus').textContent='Saved on this device.';setTimeout(()=>$('#settingsDialog').close(),500)};
$('#testConnection').onclick=async()=>{const status=$('#settingsStatus');status.textContent='Testing…';const old=settings;settings={endpoint:$('#endpoint').value.trim(),model:$('#model').value.trim(),apiKey:$('#apiKey').value.trim(),temperature:Number($('#temperature').value),systemPrompt:$('#systemPrompt').value.trim()};try{await requestAI([{role:'user',content:'Reply with only: connected'}]);status.textContent='Connected ✓'}catch(e){status.textContent=e.message}finally{settings=old}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();