// Paige secure AI proxy — Cloudflare Worker
// Add OPENAI_API_KEY as a Worker secret. Never commit it to GitHub.
const ALLOWED_ORIGINS = new Set([
  'https://imalumberjacklikemydad.github.io',
  'http://localhost:8000',
  'http://127.0.0.1:8000'
]);
function cors(origin){return{'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://imalumberjacklikemydad.github.io','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin','Content-Type':'application/json'}}
function json(body,status,origin){return new Response(JSON.stringify(body),{status,headers:cors(origin)})}
export default{async fetch(request,env){const origin=request.headers.get('Origin')||'';if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(request.method!=='POST')return json({error:'Method not allowed'},405,origin);if(origin&&!ALLOWED_ORIGINS.has(origin))return json({error:'Origin not allowed'},403,origin);if(!env.OPENAI_API_KEY)return json({error:'Server configuration is incomplete.'},500,origin);let body;try{body=await request.json()}catch{return json({error:'Invalid JSON.'},400,origin)}const messages=Array.isArray(body.messages)?body.messages.slice(-80):[];const input=messages.filter(m=>m&&['user','assistant'].includes(m.role)&&typeof m.content==='string').map(m=>({role:m.role,content:m.content.slice(0,30000)}));if(!input.length)return json({error:'No conversation supplied.'},400,origin);const payload={model:body.model||'gpt-5.6',instructions:String(body.system||'').slice(0,30000),input,temperature:Number.isFinite(Number(body.temperature))?Number(body.temperature):0.8,max_output_tokens:1800};try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)return json({error:data?.error?.message||`OpenAI request failed (${r.status})`},r.status,origin);let text=data.output_text;if(!text&&Array.isArray(data.output))text=data.output.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n');if(!text)return json({error:'OpenAI returned no text.'},502,origin);return json({text},200,origin)}catch(e){return json({error:'Could not reach the AI service.'},502,origin)}}};